// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1y5n6inyry64tc97L-A8FyYRoi70n674',
    appId: '1:597487321302:web:cf871f4aa7a17fa79e0977',
    messagingSenderId: '597487321302',
    projectId: 'houseiana',
    authDomain: 'houseiana.firebaseapp.com',
    storageBucket: 'houseiana.firebasestorage.app',
    measurementId: 'G-6439TCQQ86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCuQ-AGIHh0tYJVKSTFb02J-mWGFooyg',
    appId: '1:597487321302:android:13fa5d5a3650e9db9e0977',
    messagingSenderId: '597487321302',
    projectId: 'houseiana',
    storageBucket: 'houseiana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8lKfs11pT8GmZMOBxI72GlfCaSI9SGc',
    appId: '1:597487321302:ios:fcbab285af22f9889e0977',
    messagingSenderId: '597487321302',
    projectId: 'houseiana',
    storageBucket: 'houseiana.firebasestorage.app',
    iosBundleId: 'com.houseianaapp.users',
  );
}
