# Flutter R8/ProGuard rules for Houseiana app

# Ignore all warnings to prevent build failure from non-critical missing classes
-ignorewarnings
-verbose

# R8 specific: Add missing rules to prevent R8 from failing on missing classes
# This file can be generated by running: flutter build apk --release
# Then check: build/app/outputs/mapping/release/missing_rules.txt
#-include build/app/outputs/mapping/release/missing_rules.txt
